### ISSUE TITLE
Provide a way to choose test suites

### ISSUE THREAD

**Issue by knightsamar** [osuosl/openstack_taster#11]
Can be inside a configuration file or command-line parameters.

By default run all test suites.

**Comment by Codysseus** [comment]
The way I am going to handle this is by formatting it this way:
`openstack_taster <test_suite> <image_name>`
With `security`, `volumes`, and `all` being the options for the test suite.

**Comment by knightsamar** [comment]
...and `all` would be the default?
for `<image_name>` too the same behaviour would be desirable but that can become a seperate PR.

**Comment by Codysseus** [comment]
I wrote it so that you would have to write all, but I can make it so that you wouldn't have to.
Also, it wouldn't be too hard to write a taste_all function again. We would just need a way to generate a list of names to pass to it.

**Comment by knightsamar** [comment]
Yeah that generation of a list of images part is a bit tricky because snapshots are also saved as images but if we stick with all images created by the user which we are using to authenticate, that should be safe enough.

**Comment by Codysseus** [comment]
Well, what we could do is add metadata to images that are snapshotted and test it that way. That functionality exists on the openstack interface.

**Comment by knightsamar** [comment]
That sounds like a good idea for keeping track of our own snapshots.

**Comment by Codysseus** [comment]
Choosing test suites is handled in #13
