### ISSUE TITLE
Parameter order confusion

### ISSUE THREAD

**Issue by knightsamar** [osuosl/openstack_taster#14]
I missed this in the PR but `image_name` seems to be acceptable [either as a first parameter or a second](https://github.com/osuosl/openstack_taster/blob/master/bin/openstack_taster#L53-L58).

and the [help text](https://github.com/osuosl/openstack_taster/blob/master/bin/openstack_taster#L15-L17) add to the confusion.

It should be:
`./openstack_taster <image_name> {suite_name} [--create-image]`

The `image_name` should be *required*.
The `suite_name` would default to 'all' if not specified.~
The `--create-image` option cannot work without an `image name` so we shouldn't allow it like that. Also, we should probably rename it to `--create-snapshot` to go better with OpenStack terminologies.

**Comment by Codysseus** [comment]
Whoops, yeah I just noticed that. I'll make a small patch.
So, if the image name isn't correct, it will fail. If -c is passed with no image name or suite, then the program will quit.

**Comment by Codysseus** [comment]
#16 will fix this issue.
