### ISSUE TITLE
Expecting "no" and getting ["no","no"] fails

### ISSUE THREAD

**Issue by hodgiwabi** [osuosl/openstack_taster#15]
taster error/failure:

     ×  SSH Configuration PasswordAuthentication should eq "no"
     
     expected: "no"
          got: ["no", "no"]
     
     (compared using ==)
     
     ×  SSH Configuration ChallengeResponseAuthentication should eq "no"
     
     expected: "no"
          got: ["no", "no"]
     
     (compared using ==)

corresponding code:

      #!/bin/bash -eux

      echo "UseDNS no" >> /etc/ssh/sshd_config
      echo "PermitRootLogin no" >> /etc/ssh/sshd_config
      echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config
      echo "ChallengeResponseAuthentication no" >> /etc/ssh/sshd_config
      echo "KbdInteractiveAuthentication no" >> /etc/ssh/sshd_config
      echo "PasswordAuthentication no" >> /etc/ssh/sshd_config

**Comment by Codysseus** [comment]
So this is after running taster? Also, what do you mean corresponding code?

**Comment by knightsamar** [comment]
@DesertBeagle so that is the code which adds those settings to the sshd.conf. It lives inside a [script](https://github.com/osuosl/bento/blob/master/packer/scripts/common/sshd.sh) which is referred by a packer template [like this](https://github.com/osuosl/bento/blob/master/packer/centos-7.3-x86_64-openstack.json#L36)

We observed this while testing a CentOS image at https://github.com/osuosl/bento/pull/29#issuecomment-311141467

**Comment by Codysseus** [comment]
The problem with just appending to the file is that it might cause duplicate definitions, and ssh_config settings are only set by the first definition of a setting. The problem doesn't lie in the tests, but in the way we enable settings.

**Comment by knightsamar** [comment]
...Or we need a better matcher which equates `"no"` and `['no','no']`.

**Comment by knightsamar** [comment]
@hodgesto Have you tried using `sed` for shell that script btw ? I guess making a new matcher will take time.

**Comment by hodgiwabi** [comment]
@knightsamar I have not, I will.

**Comment by hodgiwabi** [comment]
Using `sed -i 's/PasswordAuthentication .*/PasswordAuthentication no/Ig' /etc/ssh/sshd_config` works.
Should I close this issue or are you wanting to make a better matcher regardless?

**Comment by knightsamar** [comment]
@hodgesto do the security tests ~suites~ pass with that in the shell script ?

**Comment by hodgiwabi** [comment]
@knightsamar yes they do. see https://github.com/osuosl/bento/pull/29 for the results

**Comment by knightsamar** [comment]
Excellent. Good analysis and fix @DesertBeagle and @hodgesto! 

Please close this.
