### ISSUE TITLE
CONTRIBUTING.md needs more and better content

### ISSUE THREAD

**Issue by knightsamar** [osuosl/openstack_taster#24]
* How to find things to work on ?
* How to test things if you have an OpenStack environment?  How to if you don't have one ?
* When to submit a PR ?
* How to ensure a successful PR ?

This should be more open to people outside osuosl!

@eldebrim anything to add ?

**Comment by eldebrim** [comment]
I think that's pretty much it.

**Comment by knightsamar** [comment]
Fixed by #28
