### ISSUE TITLE
ppc64-diag update test

### ISSUE THREAD

**Issue by hodgiwabi** [osuosl/openstack_taster#3]
We need to be testing all instances to have installed ppc64-diag with the latest acceptable version.

**Comment by hodgiwabi** [comment]
@knightsamar can I close this?

**Comment by knightsamar** [comment]
@hodgesto I don't remember the history behind this but the goal was just testing for the package I think this can be closed since now we test for the actual functionality implemented by the package -- which is a better way to test things.

**Comment by hodgiwabi** [comment]
Yep. Alright. Closing.
