### ISSUE TITLE
False Failures occurring in Security suite on Fedora 24

### ISSUE THREAD

**Issue by hodgiwabi** [osuosl/openstack_taster#31]
False failures occur when testing Fedora images using OpenStack_Taster

https://pastebin.osuosl.org/60581/

@knightsamar

**Comment by hodgesto** [comment]
@knightsamar

**Comment by knightsamar** [comment]
@hodgesto what fedora image did you observe this on ?

**Comment by Codysseus** [comment]
@knightsamar This is in reference to the image from this PR: https://github.com/osuosl/packer-templates/pull/16

**Comment by knightsamar** [comment]
@DesertBeagle thanks. This seems to be happening on both Fedora 24 images.
So how does inspec actually run the tests from OpenStack_taster ? Does it run as root ? Is `--sudoer` implicit ?

I ran it without `--sudoer` and got https://pastebin.osuosl.org/60701/
With `--sudoer`, I got this:  https://pastebin.osuosl.org/60696/

@hodgesto are we setting up sudoer privileges for fedora user the same way and at the same time as we did for CentOS ?

**Comment by Codysseus** [comment]
@knightsamar Looks like sudo should be added to the tests. Also, the sudo test should have a format change, and the group test should change as well.

However, the sudo check would be for the user. I don't know what to do about that.

**Comment by hodgiwabi** [comment]
@knightsamar @DesertBeagle so I realized I reverted/hadn't pushed the updated sshd.sh . The new file is uploaded on the image and taster likes it more.

- https://pastebin.osuosl.org/60706/

**Comment by knightsamar** [comment]
So I ran inspec against the instance @hodgesto newly built using this image, and it looks better:
https://pastebin.osuosl.org/60711/

You can run only the `inspec` tests as I did (would require putting your pubkey in the user's authorized_keys)

**Comment by knightsamar** [comment]
Closing this in favor of #32 describing it in detail.
