### ISSUE TITLE
Do not attach volume to hosts that are down

### ISSUE THREAD

**Issue by eldebrim** [osuosl/openstack_taster#34]
* [Log file](https://github.com/osuosl/openstack_taster/files/1166982/taster-20170721_164737-centos-le.txt)

* [gem list](https://pastebin.osuosl.org/61221/)

Reproducing the problem:
1. Shutdown one of the hosts (don't)
2. run `openstack_taster`
3. See volume tests fail

Taster tries to attach volumes to hosts even when they're down. In this case openpower1 was down for maintenance and taster tried to attach volumes to it nonetheless.  It shouldn't attempt to attach volumes to hosts when they're off.

**Comment by knightsamar** [comment]
This was addressed by #36 and #38 I believe.
