### ISSUE TITLE
Add argument to openstack_taster which is required and states what user to ssh as

### ISSUE THREAD

**Issue by ramereth** [osuosl/openstack_taster#50]
We really need is an additional argument which is required and is the user to ssh as. Then on packer-templates we can plug it in there. I'd recommend we go with ``-u`` or ``--user`` for the argument name. It can be debatable if we should have it default to the ``root` user if none is given.

**Comment by ramereth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minor feature updates to openstack_taster](https://trello.com/c/ErlAPYKw/670-minor-feature-updates-to-openstacktaster)

**Comment by Codysseus** [comment]
If it is required shouldn't it be just another regular argument?
