### ISSUE TITLE
Change image_name and ssh_user from positional arguments to flag based arguments.

### ISSUE THREAD

**Issue by Codysseus** [osuosl/openstack_taster#55]
Currently OpenStack Taster uses positional arguments like so:
```
openstack_taster <image_name> <ssh_user> {suite_name}
```
It should be changed to:
```
openstack_taster -i image_name -u ssh_user -s suite_name
```

**Comment by ramereth** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Minor feature updates to openstack_taster](https://trello.com/c/ErlAPYKw/670-minor-feature-updates-to-openstacktaster)
